### ISSUE TITLE
"trying again" doesn't?

### ISSUE THREAD

**Issue by scruffynerf** [estellaarrieta/aebn-vod-downloader#17]
When using list.txt mode, it mostly seems like when you get the "trying again" message, it doesn't really work.
It's far better to stop and restart the program, then to let it continue to run...  it looks like it mostly stops that thread.
(I do run -k, so it's pretty seamless to stop and restart, but it would be much nicer if it did cleanly re-try.)

**Comment by scruffynerf** [comment]
looks like the commented out line:
 `# self._get_manifest_content()`
shouldn't be?

**Comment by estellaarrieta** [comment]
i'll look into why that might be happenin, but _get_manifest_content() is not it, all manifest content is persistent, once we have it, there is no need to refresh it. On segment dl fail script refreshes manifest url, which is dynamic.

**Comment by scruffynerf** [comment]
well, it's working for me.  I added a check and basically it was still dying, but uncommenting that I've had zero 'stalls' still.

**Comment by estellaarrieta** [comment]
you sure? may be a coincidence. i'm fairly certain it should not matter
but if it works, it works lol

**Comment by scruffynerf** [comment]
> you sure? may be a coincidence. i'm fairly certain it should not matter but if it works, it works lol

Positive.  Went from regular stalls and having to restart as the threads stopped... to add items to the list, and walk away and it just works.  No coincidence.

**Comment by estellaarrieta** [comment]
alright, i've uncommented it
