### ISSUE TITLE
network failure causes stopping, and batch fails weirdly

### ISSUE THREAD

**Issue by scruffynerf** [estellaarrieta/aebn-vod-downloader#24]
With latest code, a 400 level error ends the download, instead of trying again (which it should do)

Also, invoking a batch, combined with the above (?), despite no logging turned on, ends up inappropriately logging, and more.
Basically, it's all confused by the failures...

ERROR:root:Exception occurred: v_XXXXXX_XXXX Download error! Response Status : 403

And then suddenly it's in DEBUG:

DEBUG:xxxxxx_8:ai_xxxxxxxx found on disk
DEBUG:xxxxxx_8:a_xxxxxxxx_6440 found on disk
DEBUG:xxxxxx_8:a_xxxxxxxx_6441 found on disk
etc etc...

(If you halt things, and restart the command, it continues everything fine, until the next error, etc etc..)

**Comment by estellaarrieta** [comment]
currently busy with other projects, will try not to forget to look into it later

**Comment by scruffynerf** [comment]
got it working smoothly again by changing line 512 in movie.py to the equiv of lines 489-493

Some minor layout changes also leading to stray extra commas in a few places.

**Comment by scruffynerf** [comment]
grr, my fix doesn't work... it finishes the file, but the video is corrupt.

**Comment by estellaarrieta** [comment]
@scruffynerf i've swapped two lines of code in the dev branch, now it reads the mainfest **after** getting a new one, not before.
Seems like aebn does not allow download of segments before we read the manifest, even if we have all the data to constuct correct segment urls. So retries are hopefully fixed.

**Comment by GadgetMasterDev** [comment]
I downloaded the code as Zip-file, and added the FFMPG into the folder. It works great, even after disruption, it picks up where it left off, @estellaarrieta nice work
